version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/Go/Gemini"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/Go/Maven"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Python/pyton"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/Rust/clock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/Rust/pime"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/Rust/rust_book"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"